server:
  port: 8030

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/categorias/**
        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/productos/**
        - id: ms-pago-service
          uri: lb://ms-pago-service
          predicates:
            - Path=/pagos/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
